name: Open Chrome Example

on: [push]

jobs:
  build:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Batch Script to Open Chrome
        run: |
          start chrome "https://www.google.com"
        shell: cmd
