name: Run Batch File

on:
  workflow_dispatch:

jobs:
  run-batch-file:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Batch File
        run: |
          powershell.exe -NoExit -Command "Start-Sleep -Seconds 60"
